[workspace]
members = ["src/rust"]

[patch.crates-io]
stellar-xdr = { git = "https://github.com/stellar/rs-stellar-xdr", rev = "e88f9fa7" }
wasmi = { package = "soroban-wasmi", git = "https://github.com/stellar/wasmi", rev = "d1ec0036" }
soroban-env-common = { git = "https://github.com/stellar/rs-soroban-env", rev = "c04c233" }
soroban-native-sdk-macros = { git = "https://github.com/stellar/rs-soroban-env", rev = "c04c233" }

[profile.release]
codegen-units = 1
lto = true
