[package]
name = "stellar-core"
version = "0.1.0"
edition = "2021"
rust-version = "1.66"

[lib]
name = "rust_stellar_core"
crate-type = ["staticlib"]

[dependencies]
log = "0.4.17"
cxx = "1.0"
im-rc = "15.0.0"
base64 = "0.13.0"
rustc-simple-version = "0.1.0"

[dependencies.soroban-env-host]
version = "0.0.12"
git = "https://github.com/dmkozh/rs-soroban-env.git"
branch = "auth_next"
features = ["vm"]

[dependencies.soroban-env-common]
version = "0.0.12"
git = "https://github.com/dmkozh/rs-soroban-env.git"
branch = "auth_next"
features = ["vm"]

[dependencies.stellar-xdr]
version = "0.0.12"
git = "https://github.com/stellar/rs-stellar-xdr"
rev = "763b104"
default-features = false

[dependencies.soroban-test-wasms]
git = "https://github.com/dmkozh/rs-soroban-env.git"
branch = "auth_next"
